### ISSUE TITLE
Angular UI Router's $state.go refresh the page in android mobile sdk

### ISSUE THREAD

**Issue by KarunaL** [Backbase/methodology-angular-development#6]
I don't know if this is the rite place to post issues related to mobile sdk. But since this issue is related to angular i am doing it.

When i change my state with $state.go. The widget engine is re-rendering my page. This issue occurs only in android Mobile SDK. I have tried this in version 1.1 and 1.3. Both versions has the same issue. I am not getting this issue in ios or desktop browsers.

**Comment by nielsmouthaan** [comment]
This is because the navigation component of the SDK is triggered because the URL has changed. This is a known issue but in some cases it can be avoided easily: don't specify a URL in the state configuration. Please let me know if this solves your issue.

**Comment by KarunaL** [comment]
I solved it by configuring my states in the way, that it does not change the default state URL. Thanks for the reply !!
